export const LOADING_BUSINESS = 'LOADING_BUSINESS'
export const LOADED_BUSINESS = 'LOADED_BUSINESS'
export const LOADING_BUSINESS_ERROR = 'LOADING_BUSINESS_ERROR'

export const SET_CURRENT_BUSINESS = 'SET_CURRENT_BUSINESS'